// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cli_sqlite3

import (
	"github.com/hayeah/goo"
)

import (
	_ "github.com/golang-migrate/migrate/v4/database/sqlite3"
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	args, err := ProvideArgs()
	if err != nil {
		return nil, err
	}
	config, err := ProvideConfig()
	if err != nil {
		return nil, err
	}
	gooConfig := ProvideGooConfig(config)
	shutdownContext, err := goo.ProvideShutdownContext()
	if err != nil {
		return nil, err
	}
	logger, err := goo.ProvideZeroLogger(gooConfig, shutdownContext)
	if err != nil {
		return nil, err
	}
	db, err := goo.ProvideSQLX(gooConfig, shutdownContext, logger)
	if err != nil {
		return nil, err
	}
	migrate, err := goo.ProvideMigrate(gooConfig)
	if err != nil {
		return nil, err
	}
	app := &App{
		Args:    args,
		Config:  config,
		DB:      db,
		Migrate: migrate,
	}
	return app, nil
}
